name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.13

    - name: Build
      run: go build main.go

    - name: Test
      run: go test 
      
    - name: deploy
      run:   go run main.go  Z>&1 &
